# coord system
TWD67 = 'TWD67'
TWD97 = 'TWD97'
SUPP_COORD_SYSTEMS = [TWD67, TWD97]

# TODO enum class
COORD_NONE = 0
COORD_TEXT = 1
COORD_KM = 2
COORD_100M = 3

trk_colors = ('White', 'Cyan', 'Magenta', 'Blue', 'Yellow', 'Green', 'Red',
                'DarkGray', 'LightGray', 'DarkCyan', 'DarkMagenta', 'DarkBlue', 'DarkGreen', 'DarkRed', 'Black')

# gpsbabel supported file extention/format mappings #########################
gpsbabel_ext_fmt = {
        ".gpx" : ("gpx",),        #GPX XML
        ".gdb" : ("gdb",),        #Garmin Mapsource
        ".mps" : ("mapsource",),  #Garmin Mapsource
        ".gtm" : ("gtm",),        #GPS TrackMaker
        ".trl" : ("alantrl", "gnav_trl", "dmtlog"),
        ".wpr" : ("alanwpr",),
        ".cst" : ("cst",),
        ".csv" : ("csv, v900, iblue747, iblue757",),
        ".wpt" : ("compegps, xmap, xmapwpt",),
        ".trk" : ("compegps", "gopal", "igo8"),
        ".rte" : ("compegps", "nmn4"),
        ".an1" : ("an1",),
        ".gpl" : ("gpl",),
        ".txt" : ("xmap2006", "garmin_txt", "pocketfms_wp", "text"),
        ".dat" : ("destinator_itn, destinator_trl, destinator_poi",),
        ".jpg" : ("exif",),      #be careful this! 
        ".ert" : ("enigma",),
        ".fit" : ("garmin_fit",),
        ".g7t" : ("g7towin",),
        ".pcx" : ("pcx",),
        ".poi" : ("garmin_goi",),
        ".gpi" : ("garmin_gpi",),
        ".tcx" : ("gtrnctr",),
        ".xml" : ("gtrnctr", "pocketfms_fp"),
        ".loc" : ("geo",),
        ".ovl" : ("ggv_ovl",),
        ".log" : ("ggv_log",),
        ".gns" : ("geonet",),
        ".kml" : ("kml",),
        ".arc" : ("arc",),
        ".wpo" : ("holux",),
        ".vpl" : ("vpl",),
        ".html": ("html",),
        ".ht"  : ("humminbird_ht",),
        ".hwr" : ("humminbird",),
        ".upoi": ("igo2008_poi",),
        ".tk"  : ("kompass_tk",),
        ".wp"  : ("kompass_wp",),
        ".ikt" : ("ik3d",),
        ".tef" : ("tef",),
        ".tr7" : ("mapasia_tr7",),
        ".mmo" : ("mmo",),
        ".bcr" : ("bcr",),
        ".mtk" : ("mtk",),
        ".tpg" : ("tpg",),
        ".tpo" : ("tpo2", "tpo3"),
        ".sbp" : ("sbp",),
        ".sbn" : ("sbn",),
        ".twl" : ("naviguide",),
        ".bin" : ("navitel_trk",),
        ".dna" : ("dna",),
        ".lmx" : ("lmx",),
        ".osm" : ("ozi",),
        ".rwf" : ("raymarine",),
        ".srt" : ("subrip",),        #SubRip subtitles for video mapping
        ".sdf" : ("stmsdf",),
        ".xol" : ("xol",),
        ".itn" : ("tomtom_itn", "tomtom_itn_places"),
        ".asc" : ("tomtom_asc",),
        ".ov2" : ("tomtom",),
        ".gpb" : ("vidaone",),
        ".vtt" : ("vitovtt",),
        ".wbt" : ("wbt",),
    }

app_syms = (
        'Unknown',
	'Water Source',
	'Waterfowl',
	'Upland Game',
	'Truck',
	'Tree Stand',
	'Treed Quarry',
	'Animal Tracks',
	'Small Game',
	'Lodge',
	'Furbearer',
	'Food Source',
	'Covey',
	'Cover',
	'Blood Trail',
	'Blind',
	'Big Game',
	'ATV',
	'Winery',
	'City Hall',
	'Ground Transportation',
	'Library',
	'Puzzle Cache',
	'Letterbox Cache',
	'Multi-Cache',
	'Triangle, Red',
	'Triangle, Green',
	'Triangle, Blue',
	'Number 9, Blue',
	'Number 9, Green',
	'Number 9, Red',
	'Number 8, Blue',
	'Number 8, Green',
	'Number 8, Red',
	'Number 7, Blue',
	'Number 7, Green',
	'Number 7, Red',
	'Number 6, Blue',
	'Number 6, Green',
	'Number 6, Red',
	'Number 5, Blue',
	'Number 5, Green',
	'Number 5, Red',
	'Number 4, Blue',
	'Number 4, Green',
	'Number 4, Red',
	'Number 3, Blue',
	'Number 3, Green',
	'Number 3, Red',
	'Number 2, Blue',
	'Number 2, Green',
	'Number 2, Red',
	'Number 1, Blue',
	'Number 1, Green',
	'Number 1, Red',
	'Number 0, Blue',
	'Number 0, Green',
	'Number 0, Red',
	'Letter D, Blue',
	'Letter D, Green',
	'Letter D, Red',
	'Letter C, Blue',
	'Letter C, Green',
	'Letter C, Red',
	'Letter B, Blue',
	'Letter B, Green',
	'Letter B, Red',
	'Letter A, Blue',
	'Letter A, Green',
	'Letter A, Red',
	'Square, Blue',
	'Rectangle, Blue',
	'Rectangle, Green',
	'Rectangle, Red',
	'Oval, Blue',
	'Oval, Green',
	'Oval, Red',
	'Diamond, Blue',
	'Circle, Blue',
	'Circle, Green',
	'Circle, Red',
	'Stump',
	'Bait and Tackle',
	'Marina',
	'Dock',
	'Dropoff',
	'Weedbed',
	'Reef',
	'Coast Guard',
	'Beacon',
	'Anchor Prohibited',
	'Wrecker',
	'Ice Skating',
	'Ski Resort',
	'Police Station',
	'Fishing Hot Spot Facility',
	'Bike Trail',
	'Block, Green',
	'Block, Blue',
	'Block, Red',
	'Pin, Green',
	'Pin, Blue',
	'Pin, Red',
	'Flag, Green',
	'Flag, Blue',
	'Flag, Red',
	'Water Hydrant',
	'Contact, Panda',
	'Contact, Glasses',
	'Contact, Clown',
	'Contact, Blonde',
	'Contact, Sumo',
	'Contact, Spike',
	'Contact, Smiley',
	'Contact, Ranger',
	'Contact, Pirate',
	'Contact, Pig',
	'Contact, Kung Fu',
	'Contact, Goatee',
	'Contact, Female3',
	'Contact, Female2',
	'Contact, Female1',
	'Contact, Dreadlocks',
	'Contact, Dog',
	'Contact, Cat',
	'Contact, Bug',
	'Contact, Biker',
	'Contact, Big Ears',
	'Contact, Ball Cap',
	'Contact, Alien',
	'Contact, Afro',
	'Geocache Found',
	'Geocache',
	'Seaplane Base',
	'Parachute Area',
	'Ultralight Area',
	'Glider Area',
	'Short Tower',
	'Tall Tower',
	'Soft Field',
	'Private Field',
	'Heliport',
	'Airport',
	'Summit',
	'Forest',
	'Beach',
	'Tunnel',
	'Oil Field',
	'Military',
	'Levee',
	'Ghost Town',
	'Crossing',
	'Civil',
	'Church',
	'Cemetery',
	'Building',
	'Bridge',
	'Toll Booth',
	'Scales',
	'Live Theater',
	'Convenience Store',
	'Zoo',
	'Department Store',
	'Stadium',
	'School',
	'RV Park',
	'Post Office',
	'Pizza',
	'Pharmacy',
	'Museum',
	'Movie Theater',
	'Fitness Center',
	'Fast Food',
	'Car Repair',
	'Car Rental',
	'Bowling',
	'Amusement Park',
	'City (Capitol)',
	'City (Large)',
	'City (Medium)',
	'City (Small)',
	'Golf Course',
	'TracBack Point',
	'Mile Marker',
	'Circle with X',
	'Flag',
	'Exit',
	'Truck Stop',
	'Trail Head',
	'Mine',
	'Lodging',
	'Shopping Center',
	'Hunting Area',
	'Car',
	'Ball Park',
	'Restricted Area',
	'Danger Area',
	'Controlled Area',
	'Dam',
	'Swimming Area',
	'Skiing Area',
	'Scenic Area',
	'Picnic Area',
	'Park',
	'Parking Area',
	'Information',
	'Medical Facility',
	'Telephone',
	'Drinking Water',
	'Shower',
	'Restroom',
	'Campground',
	'Boat Ramp',
	'Radio Beacon',
	'Dot, White',
	'Navaid, White_Red',
	'Navaid, White_Green',
	'Navaid, White',
	'Navaid, Violet',
	'Navaid, Red_White',
	'Navaid, Red_Green',
	'Navaid, Red',
	'Navaid, Orange',
	'Navaid, Green_White',
	'Navaid, Green_Red',
	'Navaid, Green',
	'Navaid, Blue',
	'Navaid, Black',
	'Navaid, Amber',
	'Man Overboard',
	'Shipwreck',
	'Waypoint',
	'Buoy, White',
	'Square, Red',
	'Square, Green',
	'Skull and Crossbones',
	'Bar',
	'Light',
	'Restaurant',
	'Residence',
	'Horn',
	'Gas Station',
	'Fishing Area',
	'Bank',
	'Diver Down Flag 2',
	'Diver Down Flag 1',
	'Diamond, Red',
	'Diamond, Green',
	'Bell',
	'Anchor',
	'POI',
	'Map Line',
	'Map Address',
	'Map Intersection',
	'Map Area',
	'Map Point',
	'Airport NDB',
	'Airport Intersection',
	'Runway Threshold',
	'VOR',
	'NDB',
	'Aviation Intersection')
