[package]
authors = ["Antonio Yang<yanganto@gmail.com>"]
name = "tile"
version = "0.1.0"

[dependencies]
quick-xml = "0.12.0"

[dependencies.pyo3]
git = "https://github.com/yanganto/pyo3.git"
branch = "#178_setter_for_non_copy_type" 

[lib]
name = "tile"
crate-type = ["cdylib"]
